apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

namePrefix: kustomized-
commonLabels:
  service: hello-world
  project: kustomize

images:
- name: service_image
  newName: docker.io/wubrgnc/kustomized
  newTag: 0.0.1

bases:
  - service.yaml
  - deployment.yaml

patchesStrategicMerge:
  - service-json-patch.yaml

patchesJson6902:
  - target:
      group: apps
      kind: Deployment
      name: hello-world
      version: v1
    path: service-inline-patch.yaml
