# Default values for buildachart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/wubrgnc/kustomized
  pullPolicy: Always

helloWorldText: Hello from this helmly service!

nameOverride: "helm-hello-world"

service:
  type: NodePort
  port: 80
  nodePort: 30082

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
